FROM alpine:3

RUN apk add -qq ccache cmake git ninja ninja-build clang20 gcc libssl3 wget bash zip gettext unzip build-base curl make libffi-dev zlib openssh autoconf linux-headers libunwind-dev

WORKDIR /opt
RUN git clone https://github.com/Microsoft/vcpkg.git
RUN VCPKG_FORCE_SYSTEM_BINARIES=1 ./vcpkg/bootstrap-vcpkg.sh
ENV PATH=$PATH:/opt/vcpkg
ENV VCPKG_TOOLCHAIN_PATH=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
ENV VCPKG_FORCE_SYSTEM_BINARIES=1
ENV GEN=ninja
ENV DUCKDB_PLATFORM=linux_amd64

WORKDIR /app
COPY vcpkg.json ./
RUN vcpkg install
COPY . ./
RUN make

FROM google/cloud-sdk:slim

WORKDIR /app
COPY --from=0 /app/build/release/extension/bigtable2/bigtable2.duckdb_extension .
RUN gzip bigtable2.duckdb_extension
