FROM debian:jessie

# Set up archive repositories
RUN echo "deb http://archive.debian.org/debian/ jessie main" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list

# Install base packages
RUN apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y --force-yes \
    build-essential \
    wget \
    tar \
    pkg-config \
    zip \
    unzip \
    libssl-dev

# Install older cmake that's more likely to work
RUN wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz && \
    tar xzf cmake-3.10.0-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local

# Install git 2.7.4
WORKDIR /tmp
RUN wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.7.4.tar.gz && \
    tar xzf git-2.7.4.tar.gz && \
    cd git-2.7.4 && \
    ./configure --prefix=/usr/local && \
    make && \
    make install && \
    cd .. && \
    rm -rf git-2.7.4*

ENV PATH=/usr/local/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/lib

WORKDIR /opt
RUN git clone https://github.com/Microsoft/vcpkg.git
RUN ./vcpkg/bootstrap-vcpkg.sh 
ENV PATH=$PATH:/opt/vcpkg
ENV VCPKG_TOOLCHAIN_PATH=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake

WORKDIR /app
COPY vcpkg.json ./
RUN vcpkg install
COPY . ./
RUN make

FROM google/cloud-sdk:slim

WORKDIR /app
COPY --from=0 /app/build/release/extension/bigtable2/bigtable2.duckdb_extension .
RUN gzip bigtable2.duckdb_extension
